name: .NET-Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build and deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}

      - name: AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: AWS CLI Update
        run: dotnet tool update -g Amazon.Lambda.Tools

      - name: Restore dependencies
        run: dotnet restore TechChallengeAuth.sln

      - name: Build
        run: dotnet build --no-restore TechChallengeAuth.sln

      - name: deploy Lambda
        id: create_package
        working-directory: ./TechChallengeAuth
        run: dotnet lambda deploy-serverless -sn TechChallengeAuth -sb tech-challenge-soat1-grp13-s3-auth

    # - name: 'Upload to S3 Bucket'
    #   run: aws s3 cp ${{ steps.create_package.outputs.package_name }} s3://tech-challenge-soat1-grp13-s3-auth
